### ISSUE TITLE
Sass variables 

### ISSUE THREAD

**Issue by ericvalois** [sharegate/sg-brand-foundations#1]
It would be nice to also have access to SASS variables as arrays. Moreover, I would separate the colors as separate array such as:
```sass
$colors-apricot: (
    apricot-lightest: #E3F0F0,
    apricot-light: #98E8DE,
    apricot: #2BBCAA,
    apricot-dark: #26A797,
    apricot-darkest: #1D9687
);
```

```sass
$colors-desktop: (
    desktop-lightest: #FFF7F2,
    desktop-light: #F8B385,
    desktop: #F47321,
    desktop-dark: #DC681F,
    desktop-darkest: #C35D1B
);
```

Concerns?

**Comment by fraincs** [comment]
I am not against it, this would add another layer of complexity to the build process of the dist files as we would need a way to maintain both final exports(.css .sass). I'm wondering what stops sass to read css4 files ant post process them.

Staying closer to the CSS spec and hand the port processing to every project needing this is part of my vision.
